services:
  service_get_products:
    build: .
    image: service_get_products
    container_name: service_get_products
    hostname: service_get_products
    restart: always 
    command: node ./build/services/products/getProducts.js
    ports:
      - 5001:5000
  service_create_products:
    build: .
    image: service_create_products
    container_name: service_create_products
    hostname: service_create_products
    restart: always 
    # volumes:
    #   - ./:/app
    command: node ./build/services/products/createProducts.js
    ports:
      - 5001:5000
    env_file:
      - .env
  db_ecommerce:
    image: postgres
    restart: always
    container_name: db_ecommerce
    hostname: db_ecommerce
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_ecommerce
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db_ecommerce"]
      interval: 5s
      timeout: 2s
      retries: 20
      