services:
  service_get_products:
    build: .
    image: service_get_products
    container_name: service_get_products
    hostname: service_get_products
    tty: true
    volumes:
      - ./app/services/products/getProducts:/app/services/products
    command: npm run server:getP
    ports:
      - 5001:5000
  db_ecommerce:
    image: postgres
    restart: always
    container_name: db_ecommerce
    hostname: db_ecommerce
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_ecommerce
    ports:
      - "5438:5432"