-- AlterTable
ALTER TABLE "Cart" ALTER COLUMN "storeId" SET DATA TYPE VARCHAR(36),
ALTER COLUMN "customerId" SET DATA TYPE VARCHAR(36);

-- AlterTable
ALTER TABLE "CartProducts" ALTER COLUMN "productId" SET DATA TYPE VARCHAR(36);
